export const env = {
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  SUPABASE_SECRET_KEY: process.env.SUPABASE_SECRET_KEY,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  APP_ENV: process.env.APP_ENV,
  ANALYSIS_API_KEY: process.env.ANALYSIS_API_KEY,
  ANALYSIS_BASE_URL: process.env.ANALYSIS_BASE_URL,
  ANALYSIS_MODEL: process.env.ANALYSIS_MODEL,
};
