-- NextAction H2.1: Runtime Failure Containment
-- Bound worker retries, persist failure metadata, and quarantine terminal
-- failures without changing the Event -> Moment domain semantics.

BEGIN;

ALTER TABLE private.events
  ADD COLUMN IF NOT EXISTS processing_attempts INTEGER NOT NULL DEFAULT 0;

ALTER TABLE private.events
  ADD COLUMN IF NOT EXISTS last_attempt_at TIMESTAMPTZ;

ALTER TABLE private.events
  ADD COLUMN IF NOT EXISTS last_failure_class TEXT;

ALTER TABLE private.events
  ADD COLUMN IF NOT EXISTS last_failure_code TEXT;

ALTER TABLE private.events
  ADD COLUMN IF NOT EXISTS last_failure_reason TEXT;

ALTER TABLE private.events
  ADD COLUMN IF NOT EXISTS last_failed_at TIMESTAMPTZ;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'events_processing_attempts_check'
      AND conrelid = 'private.events'::regclass
  ) THEN
    ALTER TABLE private.events
      ADD CONSTRAINT events_processing_attempts_check
      CHECK (processing_attempts >= 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'events_last_failure_class_check'
      AND conrelid = 'private.events'::regclass
  ) THEN
    ALTER TABLE private.events
      ADD CONSTRAINT events_last_failure_class_check
      CHECK (
        last_failure_class IS NULL
        OR last_failure_class = ANY (
          ARRAY[
            'malformed'::text,
            'permanent'::text,
            'retryable'::text,
            'retry_exhausted'::text
          ]
        )
      );
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS private.runtime_dead_letters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  queue_name TEXT NOT NULL DEFAULT 'runtime-events',
  queue_message_id BIGINT NOT NULL,
  event_id UUID,
  read_count INTEGER NOT NULL,
  enqueued_at TIMESTAMPTZ NOT NULL,
  quarantined_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  failure_class TEXT NOT NULL,
  failure_code TEXT NOT NULL,
  failure_reason TEXT NOT NULL,
  message JSONB,
  request_id UUID,
  CONSTRAINT runtime_dead_letters_queue_name_check
    CHECK (queue_name = 'runtime-events'),
  CONSTRAINT runtime_dead_letters_read_count_check
    CHECK (read_count >= 1),
  CONSTRAINT runtime_dead_letters_failure_class_check
    CHECK (
      failure_class = ANY (
        ARRAY[
          'malformed'::text,
          'permanent'::text,
          'retryable'::text,
          'retry_exhausted'::text
        ]
      )
    ),
  CONSTRAINT runtime_dead_letters_failure_code_check
    CHECK (length(btrim(failure_code)) BETWEEN 1 AND 64),
  CONSTRAINT runtime_dead_letters_failure_reason_check
    CHECK (length(btrim(failure_reason)) BETWEEN 1 AND 256),
  CONSTRAINT runtime_dead_letters_queue_message_uq
    UNIQUE (queue_name, queue_message_id)
);

ALTER TABLE private.runtime_dead_letters ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE private.runtime_dead_letters FROM PUBLIC, anon, authenticated;
GRANT ALL PRIVILEGES ON TABLE private.runtime_dead_letters TO service_role;

DROP POLICY IF EXISTS runtime_dead_letters_no_access
  ON private.runtime_dead_letters;

CREATE POLICY runtime_dead_letters_no_access
  ON private.runtime_dead_letters
  FOR ALL
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);

CREATE INDEX IF NOT EXISTS runtime_dead_letters_event_idx
  ON private.runtime_dead_letters(event_id)
  WHERE event_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS events_failure_observability_idx
  ON private.events(processing_status, last_failed_at DESC)
  WHERE processing_status = 'failed';

CREATE OR REPLACE FUNCTION private.runtime_quarantine_message(
  p_queue_message_id BIGINT,
  p_read_count INTEGER,
  p_enqueued_at TIMESTAMPTZ,
  p_message JSONB,
  p_event_id UUID,
  p_request_id UUID,
  p_failure_class TEXT,
  p_failure_code TEXT,
  p_failure_reason TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $quarantine$
DECLARE
  v_archived BOOLEAN := FALSE;
BEGIN
  INSERT INTO private.runtime_dead_letters (
    queue_name,
    queue_message_id,
    event_id,
    read_count,
    enqueued_at,
    last_seen_at,
    failure_class,
    failure_code,
    failure_reason,
    message,
    request_id
  )
  VALUES (
    'runtime-events',
    p_queue_message_id,
    p_event_id,
    GREATEST(1, p_read_count),
    p_enqueued_at,
    timezone('utc'::text, now()),
    p_failure_class,
    btrim(p_failure_code),
    btrim(p_failure_reason),
    p_message,
    p_request_id
  )
  ON CONFLICT (queue_name, queue_message_id)
  DO UPDATE
  SET
    last_seen_at = EXCLUDED.last_seen_at,
    read_count = EXCLUDED.read_count,
    failure_class = EXCLUDED.failure_class,
    failure_code = EXCLUDED.failure_code,
    failure_reason = EXCLUDED.failure_reason,
    message = EXCLUDED.message,
    request_id = EXCLUDED.request_id,
    event_id = EXCLUDED.event_id;

  -- Keep the original message in PGMQ's archive so quarantine retains the
  -- queue-native replay/audit copy as well as the failure metadata above.
  IF NOT EXISTS (
    SELECT 1
    FROM pgmq."q_runtime-events"
    WHERE msg_id = p_queue_message_id
  ) THEN
    RETURN TRUE;
  END IF;

  BEGIN
    v_archived := pgmq.archive(
      'runtime-events',
      p_queue_message_id
    );
  EXCEPTION
    WHEN OTHERS THEN
      v_archived := FALSE;
  END;

  IF v_archived THEN
    RETURN TRUE;
  END IF;

  -- A concurrent worker may have archived the same message. Treat that
  -- terminal state as success; otherwise the message remains visible for a
  -- later archival retry without losing the recorded dead letter.
  RETURN NOT EXISTS (
    SELECT 1
    FROM pgmq."q_runtime-events"
    WHERE msg_id = p_queue_message_id
  );
END;
$quarantine$;

REVOKE ALL ON FUNCTION private.runtime_quarantine_message(
  BIGINT,
  INTEGER,
  TIMESTAMPTZ,
  JSONB,
  UUID,
  UUID,
  TEXT,
  TEXT,
  TEXT
)
FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION private.runtime_quarantine_message(
  BIGINT,
  INTEGER,
  TIMESTAMPTZ,
  JSONB,
  UUID,
  UUID,
  TEXT,
  TEXT,
  TEXT
)
TO service_role;

CREATE OR REPLACE FUNCTION public.runtime_worker_tick(
  p_quantity INTEGER DEFAULT 20,
  p_visibility_seconds INTEGER DEFAULT 60
)
RETURNS TABLE (
  result_processed INTEGER,
  result_failed INTEGER
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $worker$
DECLARE
  v_message RECORD;
  v_event_id UUID;
  v_event_id_text TEXT;
  v_event_request_id UUID;
  v_process_result RECORD;
  v_process_returned BOOLEAN;
  v_processed INTEGER := 0;
  v_failed INTEGER := 0;
  v_deleted BOOLEAN;
  v_quarantined BOOLEAN;
  v_sqlstate TEXT;
  v_failure_class TEXT;
  v_failure_code TEXT;
  v_failure_reason TEXT;
  v_attempts INTEGER;
  v_now TIMESTAMPTZ;
  v_max_attempts CONSTANT INTEGER := 5;
BEGIN
  IF p_quantity < 1 OR p_quantity > 100 THEN
    RAISE EXCEPTION 'invalid worker quantity' USING ERRCODE = '22023';
  END IF;

  IF p_visibility_seconds < 5 OR p_visibility_seconds > 3600 THEN
    RAISE EXCEPTION 'invalid worker visibility' USING ERRCODE = '22023';
  END IF;

  FOR v_message IN
    SELECT msg_id, read_ct, enqueued_at, message
    FROM pgmq.read('runtime-events', p_visibility_seconds, p_quantity)
  LOOP
    -- If a previous worker durably recorded a dead letter but could not
    -- archive the queue row, finish the quarantine rather than re-running the
    -- poisoned event.
    SELECT
      dl.event_id,
      dl.request_id,
      dl.failure_class,
      dl.failure_code,
      dl.failure_reason
    INTO
      v_event_id,
      v_event_request_id,
      v_failure_class,
      v_failure_code,
      v_failure_reason
    FROM private.runtime_dead_letters AS dl
    WHERE dl.queue_name = 'runtime-events'
      AND dl.queue_message_id = v_message.msg_id
    LIMIT 1;

    IF FOUND THEN
      v_quarantined := private.runtime_quarantine_message(
        v_message.msg_id,
        v_message.read_ct,
        v_message.enqueued_at,
        v_message.message,
        v_event_id,
        v_event_request_id,
        v_failure_class,
        v_failure_code,
        v_failure_reason
      );
      v_failed := v_failed + 1;
      CONTINUE;
    END IF;

    -- Never let a malformed queue payload enter the UUID cast path.
    v_event_id := NULL;
    v_event_id_text := NULL;

    IF pg_catalog.jsonb_typeof(v_message.message) <> 'object' THEN
      v_quarantined := private.runtime_quarantine_message(
        v_message.msg_id,
        v_message.read_ct,
        v_message.enqueued_at,
        v_message.message,
        NULL,
        NULL,
        'malformed',
        'invalid_queue_message',
        'Queue message must be a JSON object.'
      );
      v_failed := v_failed + 1;
      CONTINUE;
    END IF;

    v_event_id_text := NULLIF(v_message.message->>'event_id', '');

    IF v_event_id_text IS NULL
       OR v_event_id_text !~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
    THEN
      v_quarantined := private.runtime_quarantine_message(
        v_message.msg_id,
        v_message.read_ct,
        v_message.enqueued_at,
        v_message.message,
        NULL,
        NULL,
        'malformed',
        'invalid_event_id',
        'Queue message does not contain a valid event_id.'
      );
      v_failed := v_failed + 1;
      CONTINUE;
    END IF;

    v_event_id := v_event_id_text::UUID;

    SELECT e.request_id
    INTO v_event_request_id
    FROM private.events AS e
    WHERE e.id = v_event_id
    FOR UPDATE;

    IF NOT FOUND THEN
      v_quarantined := private.runtime_quarantine_message(
        v_message.msg_id,
        v_message.read_ct,
        v_message.enqueued_at,
        v_message.message,
        v_event_id,
        NULL,
        'permanent',
        'P0002',
        'Referenced event does not exist.'
      );
      v_failed := v_failed + 1;
      CONTINUE;
    END IF;

    UPDATE private.events
    SET
      processing_status = 'processing',
      processing_attempts = processing_attempts + 1,
      last_attempt_at = timezone('utc'::text, now())
    WHERE id = v_event_id;

    BEGIN
      v_process_returned := FALSE;

      SELECT *
      INTO v_process_result
      FROM public.runtime_process_event(v_event_id)
      LIMIT 1;

      v_process_returned := FOUND;

      IF NOT v_process_returned
         OR NOT COALESCE(v_process_result.result_processed, FALSE)
      THEN
        v_failure_code := COALESCE(
          NULLIF(v_process_result.result_reason_code, ''),
          'runtime_processing_failed'
        );
        v_failure_reason := COALESCE(
          NULLIF(v_process_result.result_reason_code, ''),
          'runtime_process_event returned an unprocessed result.'
        );

        UPDATE private.events
        SET
          processing_status = 'failed',
          last_failure_class = 'permanent',
          last_failure_code = v_failure_code,
          last_failure_reason = v_failure_reason,
          last_failed_at = timezone('utc'::text, now())
        WHERE id = v_event_id;

        v_quarantined := private.runtime_quarantine_message(
          v_message.msg_id,
          v_message.read_ct,
          v_message.enqueued_at,
          v_message.message,
          v_event_id,
          v_event_request_id,
          'permanent',
          v_failure_code,
          v_failure_reason
        );

        v_failed := v_failed + 1;
        CONTINUE;
      END IF;

      v_deleted := pgmq.delete(
        'runtime-events',
        v_message.msg_id
      );

      IF v_deleted THEN
        v_processed := v_processed + 1;
      ELSE
        -- The Event has already been durably processed. Leave the message for
        -- the next visibility window so its eventual deletion is retried.
        v_failed := v_failed + 1;
      END IF;
    EXCEPTION
      WHEN OTHERS THEN
        GET STACKED DIAGNOSTICS
          v_sqlstate = RETURNED_SQLSTATE;

        v_failure_code := COALESCE(NULLIF(v_sqlstate, ''), 'XX000');

        IF v_sqlstate IN (
          'P0002',
          '22023',
          '22P02',
          '23502',
          '23503',
          '23505',
          '23514',
          '42501'
        ) THEN
          v_failure_class := 'permanent';
        ELSIF v_message.read_ct >= v_max_attempts THEN
          v_failure_class := 'retry_exhausted';
        ELSE
          v_failure_class := 'retryable';
        END IF;

        v_failure_reason := CASE
          WHEN v_sqlstate = 'P0002'
            THEN 'Referenced event does not exist.'
          WHEN v_sqlstate = '22023'
            THEN 'Runtime processing rejected an invalid parameter.'
          WHEN v_sqlstate = '22P02'
            THEN 'Runtime processing rejected an invalid value.'
          WHEN v_sqlstate = '23502'
            THEN 'Runtime processing violated a required field invariant.'
          WHEN v_sqlstate = '23503'
            THEN 'Runtime processing violated a relationship invariant.'
          WHEN v_sqlstate = '23505'
            THEN 'Runtime processing violated a uniqueness invariant.'
          WHEN v_sqlstate = '23514'
            THEN 'Runtime processing violated a data check invariant.'
          WHEN v_sqlstate = '42501'
            THEN 'Runtime processing rejected the current authorization state.'
          WHEN v_failure_class = 'retry_exhausted'
            THEN 'Runtime processing retry budget exhausted after five attempts.'
          ELSE
            'Runtime processing failed with a retryable database error.'
        END;

        UPDATE private.events
        SET
          processing_status = CASE
            WHEN v_failure_class IN ('permanent', 'retry_exhausted')
              THEN 'failed'
            ELSE 'accepted'
          END,
          last_failure_class = v_failure_class,
          last_failure_code = v_failure_code,
          last_failure_reason = v_failure_reason,
          last_failed_at = timezone('utc'::text, now())
        WHERE id = v_event_id;

        IF v_failure_class IN ('permanent', 'retry_exhausted') THEN
          v_quarantined := private.runtime_quarantine_message(
            v_message.msg_id,
            v_message.read_ct,
            v_message.enqueued_at,
            v_message.message,
            v_event_id,
            v_event_request_id,
            v_failure_class,
            v_failure_code,
            v_failure_reason
          );
        END IF;

        v_failed := v_failed + 1;
    END;
  END LOOP;

  RETURN QUERY
  SELECT v_processed, v_failed;
END;
$worker$;

REVOKE ALL ON FUNCTION public.runtime_worker_tick(INTEGER, INTEGER)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.runtime_worker_tick(INTEGER, INTEGER)
  TO service_role;

COMMIT;
